### PR TITLE
Update to Slippi 3.4.0, add nix formatter, fix builds so GitHub actions work again

### PR DESCRIPTION
**Pull request by lytedev**

### CODE REVIEW

**Review by djanatyn — APPROVED** [review]
this is wonderful 😍 thank you so much!

**Comment by lytedev** [comment]
Also added a bunch of junk to hopefully fix the GitHub actions workflows so we can leverage your Cachix cache again!

**Comment by zDEFz** [comment]
Hey I still run into build issues. Also see #44 
I changed to your repo in hope it would run.

```
$ home-manager switch
warning: updating lock file '/home/blu/.config/home-manager/flake.lock':
• Updated input 'ssbm-nix':
    'github:djanatyn/ssbm-nix/cfeb1874b437e5883272c522234d1d15cb3d3ebd' (2023-10-07)
  → 'github:lytedev/ssbm-nix/abc984d77bb41b6358f84a78b29694445d77d1d2' (2023-10-17)
• Removed input 'ssbm-nix/nix'
• Removed input 'ssbm-nix/nix/lowdown-src'
• Removed input 'ssbm-nix/nix/nixpkgs'
error: builder for '/nix/store/xlrs1fw4gm86zv2gbgg6639wvc1arfkn-slippi-ishiiruka-3.3.1-playback.drv' failed with exit code 2;
       last 10 log lines:
       >       |      ^~~~~~~~~~~~~~~~~~~~~~~~~~
       > [ 34%] Linking CXX static library libglslang.a
       > gcc-ar qc libglslang.a CMakeFiles/glslang.dir/glslang/GenericCodeGen/CodeGen.cpp.o CMakeFiles/glslang.dir/glslang/GenericCodeGen/Link.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/Constant.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/glslang_tab.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/InfoSink.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/Initialize.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/Intermediate.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/intermOut.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/IntermTraverse.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/limits.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/linkValidate.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/parseConst.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/ParseHelper.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/PoolAlloc.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/preprocessor/Pp.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/preprocessor/PpAtom.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/preprocessor/PpContext.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/preprocessor/PpMemory.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/preprocessor/PpScanner.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/preprocessor/PpSymbols.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/preprocessor/PpTokens.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/propagateNoContraction.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/reflection.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/RemoveTree.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/Scan.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/ShaderLang.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/SymbolTable.cpp.o CMakeFiles/glslang.dir/glslang/MachineIndependent/Versions.cpp.o CMakeFiles/glslang.dir/glslang/OSDependent/Unix/ossource.cpp.o CMakeFiles/glslang.dir/hlsl/hlslGrammar.cpp.o CMakeFiles/glslang.dir/hlsl/hlslOpMap.cpp.o CMakeFiles/glslang.dir/hlsl/hlslParseables.cpp.o CMakeFiles/glslang.dir/hlsl/hlslParseHelper.cpp.o CMakeFiles/glslang.dir/hlsl/hlslScanContext.cpp.o CMakeFiles/glslang.dir/hlsl/hlslTokenStream.cpp.o CMakeFiles/glslang.dir/OGLCompilersDLL/InitializeDll.cpp.o CMakeFiles/glslang.dir/SPIRV/disassemble.cpp.o CMakeFiles/glslang.dir/SPIRV/doc.cpp.o CMakeFiles/glslang.dir/SPIRV/GlslangToSpv.cpp.o CMakeFiles/glslang.dir/SPIRV/InReadableOrder.cpp.o CMakeFiles/glslang.dir/SPIRV/Logger.cpp.o CMakeFiles/glslang.dir/SPIRV/SpvBuilder.cpp.o CMakeFiles/glslang.dir/SPIRV/SPVRemapper.cpp.o
       > gcc-ranlib libglslang.a
       > [ 34%] Built target glslang
       > [ 34%] Linking CXX static library libcommon.a
       > gcc-ar qc libcommon.a CMakeFiles/common.dir/Analytics.cpp.o CMakeFiles/common.dir/BreakPoints.cpp.o CMakeFiles/common.dir/CDUtils.cpp.o CMakeFiles/common.dir/ColorUtil.cpp.o CMakeFiles/common.dir/ENetUtil.cpp.o CMakeFiles/common.dir/FileSearch.cpp.o CMakeFiles/common.dir/FileUtil.cpp.o CMakeFiles/common.dir/GekkoDisassembler.cpp.o CMakeFiles/common.dir/Hash.cpp.o CMakeFiles/common.dir/IniFile.cpp.o CMakeFiles/common.dir/JitRegister.cpp.o CMakeFiles/common.dir/MathUtil.cpp.o CMakeFiles/common.dir/MemArena.cpp.o CMakeFiles/common.dir/MemoryUtil.cpp.o CMakeFiles/common.dir/Misc.cpp.o CMakeFiles/common.dir/MsgHandler.cpp.o CMakeFiles/common.dir/NandPaths.cpp.o CMakeFiles/common.dir/Network.cpp.o CMakeFiles/common.dir/PcapFile.cpp.o CMakeFiles/common.dir/PerformanceCounter.cpp.o CMakeFiles/common.dir/Profiler.cpp.o CMakeFiles/common.dir/SettingsHandler.cpp.o CMakeFiles/common.dir/SDCardUtil.cpp.o CMakeFiles/common.dir/StringUtil.cpp.o CMakeFiles/common.dir/SymbolDB.cpp.o CMakeFiles/common.dir/SysConf.cpp.o CMakeFiles/common.dir/Thread.cpp.o CMakeFiles/common.dir/Timer.cpp.o CMakeFiles/common.dir/TraversalClient.cpp.o CMakeFiles/common.dir/Version.cpp.o CMakeFiles/common.dir/x64ABI.cpp.o CMakeFiles/common.dir/x64Analyzer.cpp.o CMakeFiles/common.dir/x64Emitter.cpp.o CMakeFiles/common.dir/MD5.cpp.o CMakeFiles/common.dir/Crypto/bn.cpp.o CMakeFiles/common.dir/Crypto/ec.cpp.o CMakeFiles/common.dir/Logging/LogManager.cpp.o CMakeFiles/common.dir/Logging/ConsoleListenerNix.cpp.o CMakeFiles/common.dir/x64FPURoundMode.cpp.o CMakeFiles/common.dir/x64CPUDetect.cpp.o CMakeFiles/common.dir/GL/GLUtil.cpp.o CMakeFiles/common.dir/GL/GLExtensions/GLExtensions.cpp.o CMakeFiles/common.dir/GL/GLInterface/GLInterface.cpp.o CMakeFiles/common.dir/GL/GLInterface/GLX.cpp.o CMakeFiles/common.dir/GL/GLInterface/X11_Util.cpp.o
       > gcc-ranlib libcommon.a
       > [ 34%] Built target common
       > make: *** [Makefile:166: all] Error 2
       For full logs, run 'nix log /nix/store/xlrs1fw4gm86zv2gbgg6639wvc1arfkn-slippi-ishiiruka-3.3.1-playback.drv'.
error: 1 dependencies of derivation '/nix/store/gdnrv32ail0ywgq43n58025ydfr4mkxl-slippi-config.drv' failed to build
error: 1 dependencies of derivation '/nix/store/i27lcg9nilhbqw90qqrabc4ag4j9zinw-home-manager-files.drv' failed to build
error: 1 dependencies of derivation '/nix/store/mh2sxfsav18rz67c9xvscfs4148lnrvj-home-manager-generation.drv' failed to build
```

**Comment by lytedev** [comment]
Very weird! This is working on both CI and my machine. https://github.com/lytedev/ssbm-nix/actions/runs/6553530681/job/17799005567

`nix run github:lytedev/ssbm-nix#slippi-netplay`

It would be hard to troubleshoot without seeing your config. Do you have any overlays that might interfere?

Edit: Responded in your issue instead: https://github.com/djanatyn/ssbm-nix/issues/44#issuecomment-1767703089

**Comment by michaelBelsanti** [comment]
This builds correctly for me, I think it should be merged

**Comment by ursi** [comment]
If anyone who this is currently working for could give me any help with #51 that would be greatly appreciated :pray:

**Comment by lytedev** [comment]
For anybody else looking for fixes from this PR, I've instead setup a new Flake focused solely on Slippi that wraps the AppImage builds instead of building from source.

See my comment here for details: https://github.com/djanatyn/ssbm-nix/issues/51#issuecomment-2138163287

**Pull request closed without merging**
